### ISSUE TITLE
500 Internal Server Error with `command` webhook

### ISSUE THREAD

**Issue by ds8k** [AndBobsYourUncle/hassio-addons#13]
I'm getting the following error when trying to use commands:

```
ERROR:flask.app:Exception on /command [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/hassio_gassistant.py", line 49, in get
    response_text, response_html = assistant.assist(text_query=message)
  File "/hassio_gassistant.py", line 132, in assist
    text_response = resp.dialog_state_out.supplemental_display_text()
TypeError: 'str' object is not callable
```

The problem appears to be this line:
```
  File "/hassio_gassistant.py", line 132, in assist
    text_response = resp.dialog_state_out.supplemental_display_text()
TypeError: 'str' object is not callable

hassio_gassistant.py - 132: text_response = resp.dialog_state_out.supplemental_display_text()
```

`supplemental_display_text` is not a function. PR #8 appears to fix this problem

**Comment by ilsalgo** [comment]
same for me :(
