### ISSUE TITLE
Would be nice if Strings could be returned when asking google a question.

### ISSUE THREAD

**Issue by chrismcneil** [AndBobsYourUncle/hassio-addons#29]
Example request /command?message=What%20is%20the%20temperature returns 500 error

ERROR:flask.app:Exception on /command [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/hassio_gassistant.py", line 49, in get
    response_text, response_html = assistant.assist(text_query=message)
  File "/hassio_gassistant.py", line 132, in assist
    text_response = resp.dialog_state_out.supplemental_display_text()
TypeError: 'str' object is not callable
INFO:werkzeug:192.168.10.7 - - [31/May/2020 15:59:45] "GET /command?message=What%20is%20the%20temperature HTTP/1.1" 500 -

**Comment by chrismcneil** [comment]
Guessing maybe this PR fixes this https://github.com/AndBobsYourUncle/hassio-addons/pull/8
